### PR TITLE
initial travis yml

### PR DESCRIPTION
**Pull request by jk234ert**
test for Travis CI, DO NOT MERGE plz

### CODE REVIEW

**Comment by MainasuK** [comment]
Please make sure this script for BouncyCastle-ObjC run without any interrupt. If the pod install process interrupt without finish the scripts. The pod cache should be cleanup at next building.

```
  s.prepare_command = <<-CMD
    BouncyCastle-ObjC/Scripts/download.sh
    BouncyCastle-ObjC/Scripts/generate.sh
  CMD
```

Test:
```
xcodebuild -workspace TesserCube.xcworkspace -scheme TesserCube -destination platform\=iOS\ Simulator,OS\=12.2,name\=iPhone\ X
```
no error on local machine: `** BUILD SUCCEEDED **`

**Comment by MainasuK** [comment]
> Wait, why is `Tessercube` changed to `TesserCube`?

From the beginning the project named is TesserCube. No one change that.
And the app display name is `Tessercube`

**Comment by MainasuK** [comment]
Maybe pod install --verbose could debug Pods installation issue

**Comment by MainasuK** [comment]
MacMini:~ MainasuK$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

JDK 1.8.201 is fine. Not sure JDK 11 works or not
@jk234ert

**Comment by jk234ert** [comment]
> MacMini:~ MainasuK$ java -version
> java version "1.8.0_201"
> Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
> 
> JDK 1.8.201 is fine. Not sure JDK 11 works or not
> @jk234ert

Seems JDK pre-installed on travis macOS env is version openjdk "12", which is not supported by latest j2objc.
Trying to manually install JDK 11 instead to fix.

**Comment by MainasuK** [comment]
Not consider just now. Maybe reopen later and make it works for Go PGP.

**Pull request closed without merging**
